export const LOAD_QUESTION_LIST_LOADING = 'LOAD_QUESTION_LIST_LOADING';
export const LOAD_QUESTION_LIST_REQUEST = 'LOAD_QUESTION_LIST_REQUEST';
export const LOAD_QUESTION_LIST_SUCCESS = 'LOAD_QUESTION_LIST_SUCCESSs';